---
- name: Setup packages
  hosts: all
  # become: yes
  tasks:
    - name: update packages cache
      ansible.builtin.apt:
        update_cache: true
      
    - name: Install pip and packages
      ansible.builtin.include_role:
        name: geerlingguy.pip

- name: Deploy redmine
  hosts: all
  # vars_files:
    # - vars.yml
  # become: yes
  tasks:
    - name: create environment variables from template
      ansible.builtin.template:
        src: env.j2
        dest: '.env'
        mode: 0644

    - name: Create network
      community.docker.docker_network:
        name: my_network

    - template:
        src: files/Caddyfile
        dest: Caddyfile

    - name: run container redmine
      community.docker.docker_container:
        name: app
        image: redmine
        published_ports: "{{ redmine_port }}:3000"
        restart_policy: always
        restart: true
        container_default_behavior: no_defaults
        pull: true
        networks:
          - name: my_network
        env_file: .env
        # env:
          # REDMINE_DB_PASSWORD: '{{ db_password }}'
          # REDMINE_DB_USERNAME: '{{ db_user }}'
          # REDMINE_DB_POSTGRES: '{{ db_host }}'
          # REDMINE_DB_PORT: '{{ db_port }}'
          # REDMINE_DB_DATABASE: '{{ db_name }}'

    - name: run container Caddy
      community.docker.docker_container:
        name: web
        image: caddy:latest
        restart_policy: always
        state: started
        volumes:
          - ./Caddyfile:/etc/caddy/Caddyfile
        networks:
          - name: my_network
        ports:
          - 80:80
          - 443:443

- name: Setting up Datadog agent
  hosts: webservers
  vars_files:
    - vars.yml
  # become: yes
  remote_user: root
  roles:
    - role: datadog.datadog
