---
- hosts: localhost
  tasks:
    - template:
        src: templates/env.j2
        dest: .env
      tags: deploy

- hosts: all
  vars_files:
    - vars.yml
  tasks:
    - name: Update system and install pip && Docker
      import_tasks: requirements.yml
      tags: setup
      become: yes

    - community.docker.docker_network:
        name: hexlet
      become: yes
      tags: deploy

    - template:
        src: .env
        dest: .env
      tags: deploy

    - template:
        src: files/Caddyfile
        dest: Caddyfile
      tags: deploy

    - community.docker.docker_container:
        name: app
        image: redmine:latest
        restart_policy: always
        state: started
        # env_file: .env
        env:
          REDMINE_DB_PASSWORD: '{{ db_password }}'
          REDMINE_DB_USERNAME: '{{ db_user }}'
          REDMINE_DB_POSTGRES: '{{ db_host }}'
          REDMINE_DB_PORT: '{{ db_port }}'
          REDMINE_DB_DATABASE: '{{ db_name }}'
        networks:
          - name: hexlet
        # ports:
          # - 80:3000
      become: yes
      tags: deploy

    - community.docker.docker_container:
        name: web
        image: caddy:latest
        restart_policy: always
        state: started
        volumes:
          - ./Caddyfile:/etc/caddy/Caddyfile
        networks:
          - name: hexlet
        ports:
          - 80:80
          - 443:443
      become: yes
      tags: deploy



