---
- hosts: all
  tasks:
    - name: Print vars
      ansible.builtin.debug:
        msg: "{{ deps }}"

    - name: Update system and install pip && Docker
      ansible.builtin.import_tasks:
        file: requirements.yml
      become: yes
