port: 80
redmine_port: 3000

pip_package: python3-pip
pip_install_packages:
  - name: docker

datadog_site: "datadoghq.eu"
datadog_api_key: "{{ datadog_api_key }}"
datadog_apm_instrumentation_enabled: "all"
datadog_checks:
  http_check:
    init_config:
    instances:
      - name: App status
        url: "http://localhost:{{ redmine_port }}"
        timeout: 5
        method: GET
