db_user: "{{ vault_db_user }}"
db_password: "{{ vault_db_password }}"
db_port: "{{ vault_db_port }}"
db_name: "{{ vault_db_name }}"
db_host: "{{ vault_db_name }}"
datadog_api_key: "{{ datadog_api_key }}"
